site_name: Tech Plus
site_url: https://techplus.readthedocs.io
site_description: Sharing the understanding, knowledge and experiences about new disruptive technologies
site_author: Tuan Duong

repo_url: https://github.com/2/techplus

theme: readthedocs

pages:
- Home: index.md
- Kubernetes: k8s.md
